function escapeHtml(s){return (s||'').replace(/[&<>"']/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function sents(text){return (text||'').replace(/\s+/g,' ').split(/(?<=[\.\?\!])\s+/).map(s=>s.trim()).filter(s=>s.split(' ').length>=5);}
function words(text){return (text.toLowerCase().normalize('NFKC').match(/\p{L}+/gu)||[]).filter(w=>w.length>3);}
function pick(a,n){a=[...a];const o=[];while(a.length&&o.length<n){o.push(a.splice(Math.floor(Math.random()*a.length),1)[0])}return o;}
function makeMCQ(sent,pool){const ws=words(sent);if(!ws.length)return null;const ans=ws[Math.floor(Math.random()*ws.length)];const stem=sent.replace(new RegExp(`\\b${ans}\\b`,'i'),'_____');const opts=[ans,...pick([...new Set(pool.filter(w=>w!==ans))],8)].slice(0,3);opts.push(ans);opts.sort(()=>Math.random()-0.5);return {type:'MCQ',q:`Apakah perkataan yang melengkapkan ayat berikut?\n“${stem}”`,options:opts,answer:ans};}
function makeDD(sent){const ws=words(sent);if(ws.length<4)return null;const blanks=pick([...new Set(ws)],Math.min(3,Math.max(2,Math.floor(ws.length/6))));let stem=sent;blanks.forEach(w=>{stem=stem.replace(new RegExp(`\\b${w}\\b`,'i'),'_____')});const bank=blanks.sort(()=>Math.random()-0.5);return {type:'DD',q:`Seret & lepas perkataan betul ke tempat kosong:\n“${stem}”`,blanks:blanks,bank};}
function generateQuizFromTranscript(text){const pool=words(text), ss=sents(text);const list=[];if(!ss.length)return list;for(let i=0;i<6;i++){const s=ss[i%ss.length];if(i%2===0){const dd=makeDD(s);if(dd){list.push(dd);continue;}}const mcq=makeMCQ(s,pool);if(mcq)list.push(mcq);}return list;}
function renderQuiz(list){const wrap=document.getElementById('quizWrap');if(!wrap)return;if(!list.length){wrap.innerHTML='<div class="status">Transkrip belum cukup untuk jana kuiz.</div>';return;}wrap.innerHTML='';list.forEach((it,idx)=>{if(it.type==='MCQ'){const card=document.createElement('div');card.className='quiz-card';card.innerHTML=`<div><b>Soalan ${idx+1}</b> <small class="muted">(MCQ)</small></div><div style="white-space:pre-wrap;margin-top:6px">${escapeHtml(it.q)}</div><div class="quiz-options"></div>`;const ow=card.querySelector('.quiz-options');it.options.forEach(op=>{const b=document.createElement('button');b.type='button';b.className='quiz-option';b.textContent=op;b.addEventListener('click',()=>{const ok=(op.toLowerCase()===it.answer.toLowerCase());b.classList.add(ok?'correct':'wrong');});ow.appendChild(b);});wrap.appendChild(card);}else if(it.type==='DD'){const card=document.createElement('div');card.className='quiz-card';card.innerHTML=`<div><b>Soalan ${idx+1}</b> <small class="muted">(Seret & Lepas)</small></div><div style="white-space:pre-wrap;margin-top:6px">${escapeHtml(it.q)}</div><div class="dd-targets"></div><div class="dd-bank"></div>`;const targets=card.querySelector('.dd-targets');const bank=card.querySelector('.dd-bank');it.blanks.forEach(ans=>{const slot=document.createElement('div');slot.className='dd-slot';slot.dataset.answer=ans.toLowerCase();slot.addEventListener('dragover',e=>e.preventDefault());slot.addEventListener('drop',e=>{const t=e.dataTransfer.getData('text/plain');slot.textContent=t;slot.style.borderColor=(t.toLowerCase()===slot.dataset.answer)?'#43a047':'#e53935';});targets.appendChild(slot);});it.bank.forEach(w=>{const chip=document.createElement('div');chip.className='dd-chip';chip.textContent=w;chip.draggable=true;chip.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',w);});bank.appendChild(chip);});wrap.appendChild(card);}});}
document.getElementById('btnGenQuiz')?.addEventListener('click',()=>{const txt=document.getElementById('transkrip')?.value||'';renderQuiz(generateQuizFromTranscript(txt));});
